Documentation/Reference/Types/Index.rst

The "--newline--" setting for part 3 was broken ever since. It was also documented wrong,
the correct setting would have been "newline" without the dashes. The underlying parsing
code dates back to Kasper's initial revision and was never touched or modified. The
according parsing code will be removed with CMS 7 and this documentation part can be
removed without substitution - also in 6.2 since it never worked anyway.

[BUGFIX] Remove broken palette "newline" documentation

---

Documentation/Reference/Columns/Flex/Index.rst

currentSheetId as meta flex form field was never fully implemented
correctly in the core and is now removed.

Flex: Remove currentSheetId

---

Documentation/ExtendingTca/StoringChanges/Index.rst

TCA Overrides are not possible with the old TCA setup via dynamicConfigFile in ext_tables.php,

[TASK] Warn about TCA overrides with dynamicConfigFile

---

Documentation/Reference/Columns/Group/Index.rst

Extbase expects "foreign_table" to contain exactly one table name compared to "allowed" which can hold a list of table names.

[BUGFIX] Mention one table limit of foreign_table

---

Documentation/AdditionalFeatures/CoreWizardScripts/Index.rst

The link wizards also accepts which fields should be blinded,
but the documentation for this param is missing.
https://forge.typo3.org/issues/69462

[TASK] Add missing blindLinkFields to the core link wizard

---

Documentation/Reference/Ctrl/Index.rst

The headline and chapter 'typeicons' doesn't exist any more.
Remove references to that chapter.

[BUGFIX] Remove refs to 'typeicons'

---

Documentation/Reference/Columns/Select/Index.rst

Remove the deprecated renderMode from the TCA select documentation and
replace it with the mandatory renderType property. Add a note that
maxitems property is ignored if the renderType is `selectSingle`.
Related: #58521
Related: #69822

[TASK] Update `select` renderType and maxitems documentation

---

Documentation/Reference/Columns/Inline/Index.rst

`maxitems` is defaulted to 1, trough `checkValue_checkMax` here: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2-15/typo3%2Fsysext%2Fcore%2FClasses%2FDataHandling%2FDataHandler.php#L2927

[FIX] Inline element with foreign_table only has maxitems 1 as default

---

Documentation/Reference/Columns/Group/Index.rst

Within "foreign_table" only a single table name is allowed while "allowed" can hold a list of table names.

[TASK] Backport foreign_table appendix from master

---

Documentation/Reference/Columns/Input/Index.rst

Previous documentation was a copy/paste of ``range`` option which was clearly a mistake.
Description is directly taken from Changelog notes (Feature 28243)

Document ``disableAgeDisplay`` option

---

Documentation/Reference/Columns/Inline/Index.rst

The disposal of the properties foreign_sortby and symmetric_sortby
are only available for persisting the parent reference with the child,
thus using the property foreign_field. In a comma-separated-value
approach this does not work.

[TASK] Point out the scope of foreign_sortby and symmetric_sortby

---

Documentation/ExtendingTca/Examples/Index.rst

Using the third parameter in addTCAcolumns is deprecated, remove it.

Remove third parameter in addTCAcolumns()

---

Documentation/Reference/Columns/Input/Index.rst

The default value for max is hardcoded to 256 which should be mentioned.

[BUGFIX] Document default max length for input

---

Documentation/Reference/Columns/Common/Index.rst

The common property "search" has to be located **inside** of the config-array. It's not a sibling like the example showed before.

Fix wrong TCA example (common properties > search)

---

Documentation/Reference/Columns/Index.rst

There are two equal signs when assigning a value to an array but there must be only one.

Fix syntax error in displayCond example code

---

Documentation/Reference/Types/Index.rst

As the columnsOverrides gets merged with the entire column config, you must also include the 'config' dimension in the array you want to overrule.

columnsOverride was missing config level

---

Documentation/Reference/Ctrl/Index.rst

The extension extdeveval is outdated for quite some time,
therefore it should not be mentioned in the documentation
any more.

[TASK] Remove reference to outdated extension extdeveval

---

Documentation/Reference/Columns/Group/Index.rst

As the filter attribute doesn't work in combination with a wizard, I've added a note in the filter section to be aware of this reasons for exclusion.

Update index.rst with hint for filter attribute

---

Documentation/AdditionalFeatures/SoftReferences/Index.rst
Documentation/Reference/Columns/Select/Index.rst

Documented:
* https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.3/Breaking-77081-RemovedTCASelectTreeOptions.html
* https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.3/Breaking-77156-TSconfigAndTStemplateSoftReferencesFunctionalityRemoved.html

[TASK] Updated docs for TYPO3 8.3

---

Documentation/Reference/Columns/Select/Index.rst

Table structure for table 'user_testmmrelations_two_rel_mm' has a syntax error near ')' at line 13.

[BUGFIX] Fix SQL syntax error in example

---

Documentation/AdditionalFeatures/WizardsConfiguration/Index.rst

Add the missing documentation of maxItemsInResultList, which has always been available.
Needs to be backported to 7.6 and 6.2.

Add maxItemsInResultList for SuggestWizard

---

Documentation/ColumnsConfig/Type/Inline.rst

To add custom configuration for the file abstraction layer the overrideChildTca has to be used instead of foreign_types.

Update custom configuration for FAL

---

Documentation/ColumnsConfig/Properties/GroupSuggestOptions.rst

The code example for `suggestOptions` still contained the old code for wizards[suggest]

Fix `suggestOptions` code example

---

Documentation/Reference/Ctrl/Index.rst

Fixed smaller inconsistencies in example of [ctrl][title].
Solves #156.

Fixed example of [ctrl][title]

---

Documentation/Reference/Columns/Select/Index.rst

Adds crucial renderType to selectMultipleSideBySide example

Missing crucial renderType in example

---

Documentation/Reference/Columns/Group/Index.rst

see also related https://review.typo3.org/#/c/55107/ and https://forge.typo3.org/issues/83355 for arguments as to why this is wrong.

[BUGFIX] Fix wrong description of FAL as type group

---

Documentation/Introduction/Index.rst

The sections "Properties scope" and "Glossary" are not related to "TCA main array structure".

[BUGFIX] Fix level of sections in introduction

---

Documentation/ColumnsConfig/FieldControl/LinkPopup.rst

The blindLinkOption "Folder" is missing in the documentation. With this patch it get's added.

Add missing blindLinkOptions "folder"

---

Documentation/Ctrl/CtrlPrependAtCopy.rst

The string given here is appended, not prepended to the title of the original record.

[BUGFIX] Clarify misnamed prependAtCopy option

---

Documentation/Columns/ColumnsExclude.rst.txt
Documentation/Ctrl/CtrlTitle.rst.txt
Documentation/Settings.cfg

Inside TYPO3 manual has been merged with TYPO3 Core API.
The references are updated.

Change links from t3inside to t3coreapi

---

Documentation/Ctrl/CtrlLabelUserfunc.rst.txt

The code shows, that the parent object is no longer passed to the user function.See \TYPO3\CMS\Core\Utility\GeneralUtility::2195 as example. So there is no need to mention it in this documentation.

Remove the mention to the parent object

---

Documentation/ColumnsConfig/Behaviour/AllowLanguageSynchronization.rst

The removed and the included text are nearly the same. There are tiny differences ("whether" vs. "if"). So if you think I removed the wrong of them, feel free to reject my pull request and change it the other way.

Remove duplicate text block

---

Documentation/Ctrl/CtrlLabel.rst.txt

To show up, that this issue does not apply to a certain field, the warning message is now written more general

Rephrase the warning message (latest)

---

Documentation/ColumnsConfig/Type/User.rst

It fixes small typo in TCA sample code where comma was missing. It adds missing comma.

Add missing comma in TCA configuration example

---

Documentation/ColumnsConfig/Properties/TextFormat.rst.txt

Current list for formats from: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/t3editor/Configuration/Backend/T3editor/Modes.php
Corrections:
- Remove double html entry
- Remove unsupported formats sparql and mixed
- Sort alphabetically

Correct available t3editor formats

---

Documentation/ColumnsConfig/Properties/SlugGeneratorOptions.rst.txt

Add missing documentation for Feature: #88198 - TCA-based Slug modifiers for extensions
see ChangeLog:  https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-88198-TCA-basedSlugModifiersForExtensions.html

TCA-based Slug modifiers for extensions

---

Documentation/ColumnsConfig/Type/Check.rst

Before, all the screenshots (how it looks) were displayed first
and then all the code examples.
This change displays the source snippet directly under the screenshot.
Additionally:
- add 2 examples for FlexForms (using the exact same functionality as the TCA in PHP)
- add a 1 line description pointing out what differentiates each
example from the others
- add headlines as separators

Rearrange examples on checkbox page

---

Documentation/ColumnsConfig/Type/Check.rst

In a previous change, headers were introduced for the examples. Though
the new headers followed the conventions for header levels, this was
not in sync to headers already used in included subfiles. Due to this,
the header levels got mixed up and some headers were not displayed.

[BUGFIX] Fix header levels for type=check

---

Documentation/ColumnsConfig/Type/Check.rst

- Due to previous change, subheaders for examples for added. Because existing headers
for level 3 do not conform to standard type ('-----'), we must change the header
levels here
Releases: master, 10.4

Fix header levels for check type

---

Documentation/ColumnsConfig/Properties/ImageManipulationCropVariants.rst.txt

This commit adds cropVariants documentation about configuration per content element, configuration per content element type, disabling cropVariants and using cropVariants in Fluid's image view helper.
This is just copy & paste of a few sections from TYPO3 CMS Core ChangeLog item [Feature: #75880 - Implement multiple cropping variants in image manipulation tool](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Feature-75880-ImplementMultipleCroppingVariantsInImageManipulationTool.html)

Update cropVariants documentation of imageManipulation type

---

Documentation/ColumnsConfig/Properties/SlugAppearance.rst.txt
Documentation/ColumnsConfig/Type/Slug.rst

See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-89573-AllowFlexibleBaseUrlForSlugFieldsInFormEngine.html

[FEATURE] Add appearance to TCA slug type

---

Documentation/Ctrl/CtrlSearchFields.rst.txt

Make it more clear which part of the documentation is meant.

Rephrase reference to 'search' option

---

Documentation/Types/Index.rst

The explanation was listing the tab label as a field. Change it so the explanation explicitly define the tab labels and fixed the fields listing.

Fix erroneous explanation in TCA Types and add more details

---

Documentation/ColumnsConfig/Behaviour/CommonAllowLanguageSynchronization.rst.txt
Documentation/ColumnsConfig/Type/Flex.rst
Documentation/ColumnsConfig/Type/Group.rst
Documentation/ColumnsConfig/Type/ImageManipulation.rst
Documentation/ColumnsConfig/Type/Inline.rst
Documentation/ColumnsConfig/Type/Radio.rst
Documentation/ColumnsConfig/Type/checkDefault.rst
Documentation/ColumnsConfig/Type/checkboxLabeledToggle.rst
Documentation/ColumnsConfig/Type/checkboxToggle.rst
Documentation/ColumnsConfig/Type/inputColorPicker.rst
Documentation/ColumnsConfig/Type/inputDateTime.rst
Documentation/ColumnsConfig/Type/inputDefault.rst
Documentation/ColumnsConfig/Type/inputLink.rst
Documentation/ColumnsConfig/Type/inputRsaInput.rst
Documentation/ColumnsConfig/Type/selectCheckBox.rst
Documentation/ColumnsConfig/Type/selectMultipleSideBySide.rst
Documentation/ColumnsConfig/Type/selectSingle.rst
Documentation/ColumnsConfig/Type/selectSingleBox.rst
Documentation/ColumnsConfig/Type/selectTree.rst
Documentation/ColumnsConfig/Type/textDefault.rst
Documentation/ColumnsConfig/Type/textT3editor.rst
Documentation/ColumnsConfig/Type/textTextTable.rst

This concerns properties that are not direct properties of
['columns']['config'] but are subproperties of one of the
listed properties.
For example:
* ['columns']['config']['behaviour']['allowLanguageSynchronization']
* ['columns']['config']['fieldWizard']['defaultLanguageDifferences']
Before everything was listed in one list, which made it easy to get
this mixed up.
Now,
- the subproperties have a title which includes the property
- each property with subproperties has a small table of contents
listing the possible subproperties
Resolves: #296
Resolves: #260
Releases: master, 10.4, 9.5

Make subproperties in columnConfig more easily visible

---

Documentation/ColumnsConfig/Properties/InputRange.rst.txt

1. The value stored in the database will be in UTC. Thus the range values should also be defined in UTC.
2. `23, 59, 59, 12, 31, 2020` includes the whole day for `upper`

Use gmmktime to define date range

---

Documentation/Ctrl/CtrlTypeiconClasses.rst.txt

See Core Feature 90042
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845
As in case of `pages` typeicon_classes needs to be extended to handle all cases, we should cross-link that documentation.

[TASK] Add Cross-Link to PageTypes

---

Documentation/ColumnsConfig/Type/inputColorPicker.rst

As used in the example the correct `renderType` is `colorpicker` (lowercase; no lowerCamelCase).

[TASK] Replace `colorPicker` with `colorpicker`

---

Documentation/ColumnsConfig/Type/Slug.rst

The statement about RealURL is incorrect: path segments there can contain slashes if the whole path is overwritten, just like slugs. Therefore the statement provides false information about RealURL and should be removed.

Remove false information about RealURl from Slug.rst

---

Documentation/Columns/ColumnsL10nMode.rst.txt

Documentation of l10n_mode mentions l10n_display setting with value 'defaultAsRead**O**nly'. The value of the setting is case sensitive and must be 'defaultAsRead**o**nly'.
This also affects 10.4 and 9.5 branches. Should I create separate Pull Requests for those or is there a merge strategy which allows to apply the patch to multiple branches?

[BUGFIX] Fix case of mentioned defaultAsReadonly value

---

Documentation/Index.rst
Documentation/Settings.cfg
Documentation/Targets.rst
Documentation/genindex.rst

- Add link targets to start page and remove from main menu (as decided
on Slack)
- remove "Previous key" (as decided on Slack)
- Remove some information from start page that is already displayed via
the theme, e.g. in the footer, specifically: version, copyright, email
etc.
- Add a link to the sitemap
- Update the texts (e.g. upon finding a bug, the preferred behaviour is
NOT to send an email).

[FEATURE] Improvements to start page

---

Documentation/ColumnsConfig/Properties/SlugEval.rst.txt

Also move the hint about combining keywords to make it clear it refers to all of them, not only the last.

Fix remaining indentation of slug eval options

---

Documentation/Examples/About.rst
Documentation/Examples/Index.rst

Resolves #364
In pages with a toctree directive the document title should be the only headline.

Fix toctree nesting

---

Documentation/ColumnsConfig/Type/Input/Properties/Range.rst

Validation of "range" does not happen only server-side, it also gets validated in the JS that handles the form.

[DOC] Remove incorrect info box

---

Documentation/ExtendingTca/Examples/Index.rst
Documentation/ExtendingTca/Index.rst
Documentation/ExtendingTca/StoringChanges/Index.rst
Documentation/ExtendingTca/Verifying/Index.rst

"Extending TCA" was moved to "TYPO3 Explained" since version 8.7.
The outdated pages in TCA reference are still often listed as top results
for search.
This is a fix for directing users to the newer information.
Depends on: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1371
Releases: 7.6

[TASK] Ask information about change in location Extending TCA (7.6)

---

Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst

The link popup for input fields was long ago changed to be opened with a modal.
The windowOpenParameters have no effect whatsoever.
Also correct some words.

Remove windowOpenParameters in inputLink

---

screenshots.json

Lately some action signatures have changed:
setScreenshotsDefaultPid -> setNavigationDefaultPid
setScreenshotsDefaultTable -> setNavigationDefaultTable
setScreenshotsDefaultUid -> setNavigationDefaultUid
clearScreenshotsDefaults -> clearNavigationDefaults
{"action": "createPhpArrayCodeSnippet", .. "field": "columns/title" ..}
->
{"action": "createPhpArrayCodeSnippet", .. "fields": ["columns/title"] ..}
{"action": "createYamlCodeSnippet", .. "field": "services/_defaults" ..}
->
{"action": "createYamlCodeSnippet", .. "fields": ["services/_defaults"] ..}
{"action": "createXmlCodeSnippet", .. "field": "T3DataStructure/meta" ..}
->
{"action": "createXmlCodeSnippet", .. "nodes": ["T3DataStructure/meta"] ..}
See repository https://github.com/TYPO3-Documentation/t3docs-screenshots for further …

[TASK] Adapt action signatures

---

Documentation/Columns/Properties/DisplayCond.rst

The PHP example code in "A complex example" is part of an array declaration, so it must not end with a `;` but with a `,`

[BUGFIX] Replace semicolon by comma

---

Documentation/ColumnsConfig/CommonProperties/LocalizeReferencesAtParentLocalization.rst

The TCA option localizeReferencesAtParentLocalization only works if
the field is NOT stored in a MM table.
Also add the select field as a possible type, as it works with all
fields defining foreign_table.

[BUGFIX] Fix inverted description

---

Documentation/ColumnsConfig/Type/Inline/Properties/Index.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ShowNewRecordLink.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94765-IntroduceShowNewRecordLinkOption.html?

[Feature] #94765 - Introduce showNewRecordLink option

---

Documentation/ColumnsConfig/Type/Check/Properties/Items.rst

The second entry is not needed for checkboxes.
This has been already simplified in core.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/72056
And styleguide:
https://github.com/TYPO3/styleguide/pull/243

[TASK] Remove mentions of empty check items value

---

Documentation/Types/Properties/Showitem.rst

The rendering will replace `--` with `–` in order to help editors, just like quotation marks.
In this case we want to have actual code examples.
That's why we now add proper code syntax.

Fix rendering of -- in showitem

---

Documentation/ColumnsConfig/Type/Group/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/InternalType.rst

Not everything has been cleaned up in commit eea5007.
This removes the leftover places, where internal_type
is mentioned as required.

[TASK] Remove leftovers of internal_type as required

---

Documentation/ColumnsConfig/Type/Group/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst

The option elementBrowserAllowed was designed for group fields
to override the allowed extension list. It has no effect if used
directly on inline fields.
The further explanation about the "Add media by URL" button is
moved to the group field.
Also fix some typos and links while at it.

[TASK] Remove elementBrowserAllowed from type inline

---

Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst

headerThumbnail is not a boolean, but an associative array.
This patch fixes the data type and adds the missing options.

[TASK] Fix appearance->headerThumbnail data type

---

Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst

The pid setting does only work for controls like AddRecord or similar.
Links do not create a new record and hence do not need a target pid.
This is very likely a copy/paste error from back then.

[BUGFIX] Remove unavailable pid option in linkPopup

---

Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst

This option was added with the introduction of FAL in TYPO3 v6.
It has been forgotten to add it to the documentation.
Fixes: #350

[TASK] Document appearance->createNewRelationLinkTitle type=inline option

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Properties/FileFolderConfig.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

fileFolder => fileFolderConfig.folder
fileFolder_recursions => fileFolderConfig.depth
fileFolder_extList => fileFolderConfig.allowedExtensions

[BUGFIX] Rename old configuration keys of fileFolderConfig

---

Documentation/ColumnsConfig/Type/Slug/Properties/GeneratorOptions.rst

This option is used for core page records to create the
usual /foo/bar/baz url path. This feature does not work
for any other table and will be simply ignored.

[TASK] Add hint for prefixParentPageSlug option

---

Documentation/ColumnsConfig/Type/Inline/Properties/ForeignTable.rst

The deprecation for foreign_table => sys_language does
only apply to type=select.

[BUGFIX] Remove wrongly placed deprecation notice

---

Documentation/ColumnsConfig/Type/Text/Properties/EnableTabulator.rst
Documentation/ColumnsConfig/Type/Text/Properties/FixedFont.rst

The examples for enableTabulator and fixedFont were incorrect.
The correct code snippet from styleguide is "text15".
As a drive-by: Fix render type list.

[BUGFIX] Use correct code snippets/images

---

Documentation/Ctrl/CtrlTypeiconClasses.rst.txt
Documentation/Ctrl/CtrlTypeiconColumn.rst.txt

[BUGFIX] Correct default icon usage in `typeicon_classes`

---

Documentation/Settings.cfg
Settings.cfg

they don't exist anymore, anyway
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/171
releases: 7.6

[TASK] Remove commented out references

---

Documentation/Ctrl/Properties/TypeiconClasses.rst
Documentation/Ctrl/Properties/TypeiconColumn.rst

change of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/525 applied for main
releases: main, 11.5

[BUGFIX] Correct default icon usage in typeicon_classes

---

Documentation/Ctrl/Properties/Type.rst

I want to search for [$GLOBALS['TCA']['tx_news_domain_model_news']['ctrl']['type'].
It is only searchable if the title matches exactly the TCA array key name!

Do not use "record type" as the title.

---

Documentation/Ctrl/Properties/Sortby.rst

The current markup/rendering does not really convey the importance of using this field propertly:

Raise attention on ctrl/sortby

---

Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSortby.rst

This mirrors ctrl/sortby since the same mistakes can be done here.
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/545

Raise attention on inline foreign_sortby

---

Documentation/ColumnsConfig/Type/Inline/Properties/ShowNewRecordLink.rst

Truly this is breaking, but this option is not so old
and probably hasn't many references to it if any at all.

[BUGFIX] Fix typo in ShowNewRecordLink ref

---

Documentation/ColumnsConfig/Type/Select/Properties/Items.rst

With #91008 the itemGroups were introduced and were squeezed
between optional icon (position 3) and optional description
(position 4). This caused changing array keys, but was unfortunately
not marked as breaking.
This patch adds a hint, that positions have changed since TYPO3 v10
and adjustments are necessary.

[BUGFIX] Document breaking behaviour of select items

---

Documentation/Ctrl/Properties/Index.rst
Documentation/Ctrl/Properties/Label.rst
Documentation/Ctrl/Properties/LabelAlt.rst
Documentation/Ctrl/Properties/LabelAltForce.rst

solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/518

[BUGFIX] Bring label_alt and label_alt_force back to menu

---

Documentation/Ctrl/Properties/SearchFields.rst

Since the introduction of new TCA types also the
available types for searchFields have changed.
The note with eval has been changed to mention
the according new types instead.
Fixes: #552

[TASK] Add new TCA types to searchFields

---

Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst

This option is available since TYPO3 v10.
See the according Changelog here:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.1/Feature-84250-SeparatelyEnableDisableAddMediaByURLAndSelectUploadFiles.html

[TASK] Document fileByUrlAllowed

---

Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst

This option has been removed way back in TYPO3 v7.
Changelog file:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/7.4/Breaking-68116-DropRTEuserLinksFunctionality.html
Releases: 11.5, 10.4, 9.5

[TASK] Remove unavailable "spec" linkHandler

---

Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst

New example for the TCA configuration of the fieldControl linkPopup.
This is helpful as the documentation does not specify that the options
are in another array with the key `options`.

[TASK] Add example to linkPopup fieldControl documentation

---

Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst

The inconsistent indents resulted the content to be rendered
as quotes in some places.
Related: TYPO3-Documentation/T3DocTeam#150
Releases: main, 11.5, 10.4, 9.5
---
not part of commit message:
see rendered page: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Flex/FlexformSyntax.html 
**Note**: 4 spaces was used here because that is what is predominant on that page and in TCA reference. I made minimal changes only so much so that the quotes will no longer be used. In any case, the indenting should probably be unified at some point, see also https://github.com/TYPO3-Documentation/T3DocTeam/issues/191

Fix inconsistent indents

---

Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst

Use ::class with class name instead of static string in the description
of the property eval.
Some captions reflecting the file names are added to the code blocks.
Resolves: #599
Resolves: #252

Replace class name in static string in eval (v11 branch)

---

Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst

Use ::class with class name instead of static string in the description
of the property eval.
Additionally, "required" is removed from the string, since this has been
moved to a separate property since v12.
Some captions reflecting the file names are added to the code blocks.
For v12, we can also add a "use" to ext_localconf.php to define the
full class name and use the short class name below.
Resolves: #599
Resolves: #252
---
Do not backport this PR - patches for other branch 11.5 will be supplied with a separate PR.

Replace class name in static string in eval (v12 / main branch)

---

Documentation/Ctrl/Properties/Container.rst

The control container page is improved by changing some
formatting and adding clarifications:
1. In the code snippets, if one is not familiar (yet)
with the example, it is difficult to distinguish
between strings which should be used verbatim (as is)
such as "renderType" and strings which are used as
placeholders. This patch changes the placeholder
strings to be enclosed in angle brackets <>. Since this
is in a string, it should not be a problem for
the lexers when performing the syntax highlighting.
Mostly, this was done for <containerRenderType> where
a valid container render type should be inserted.
2. For the explanation of the parts in the code snippet,
a definition list is used which results in better
formatting, highlighting the string which is explained
3. The containerRenderType …

Clarify ctrl | container page

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst

Use short form [] instead of array() as is customary
in TYPO3 core.

Replace array notation

---

Documentation/ColumnsConfig/Type/Inline/Examples.rst
Documentation/ColumnsConfig/Type/Inline/Index.rst
Documentation/Ctrl/Properties/Container.rst

As pointed out differently, fieldInformation and fieldWizard must
be configured differently for type inline. An example is added
to address this. Also, a note is added in the description and
several links linking between the various places where this is
relevant.
Resolves: #186
-----
Not in commit: except for the "use" in ext_localconf.php, I think this could also be backported to v11.

Add example for fieldInformation for type inline

---

Documentation/Ctrl/Properties/Enablecolumns.rst

[BUGFIX] Link to restriction builder in TYPO3 Explained correctly

---

Documentation/CodeSnippets/Manual/Ctrl/DataHandlerFields.rst.txt

Displayed is a TCA snippet, not a backend route. Included,
for example, on tstamp page:
https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/Ctrl/Properties/Tstamp.html

[BUGFIX] Correct caption of code snippet

---

Documentation/Columns/Properties/Exclude.rst

The example does not show the property èxclude`. So it has no added value for the user.
I think 'exclude' is self-explanatory enough that it doesn't need an example/image to illustrate its use.

Remove inappropriate example

---

Documentation/ColumnsConfig/Type/Category/Index.rst

While the documentation states that you can override some fields, I feel the need to indicate that there are edge cases where `type=category` is not suitable. What do you think?
Is it possible to add the hacktoberfest-accepted label?

Add edge case info about category type

---

Documentation/codesnippets.php
composer.json

In the Documentation Folder so we can place generated files anywhere not just in this context
Introduce composer scripts for codesnippet generation, move bin to .Build, sort packages
Update all codesnippets - no updates needed
references #670

[Backport 11.5][TASK] Move Codesnippets.php

---

Documentation/ColumnsConfig/Type/None/Properties/PassContent.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/310
Releases: main

[DEPRECATION] #99523 - Deprecate type="none" pass_content

---

Documentation/ColumnsConfig/Type/User/Index.rst

"EXT:reaction" was plain wrong, as it's an outdated extension. So the module name was mistaken as extension name. The new system extension is "webhooks" and consists of 2 modules: reactions and webhooks.

correct extensionKey for system extension with example

---

Documentation/ColumnsConfig/Type/User/Index.rst

Added a note, that custom formengine elements must contain valid HTML, since unexpected problems may occur if not.
Details: https://forge.typo3.org/issues/100943

Add important note about custom formengine elements

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/CommonProperties/Search.rst
Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

The referenced QueryHelper class is gone, therefore the corresponding sentences are adjusted.
This solves the following warnings:
./Documentation/ColumnsConfig/CommonProperties/Mm.rst:120: WARNING: undefined label: t3coreapi:database-query-helper-quotedatabaseidentifiers
./Documentation/ColumnsConfig/CommonProperties/Search.rst:53: WARNING: undefined label: t3coreapi:database-query-helper-quotedatabaseidentifiers
./Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst:139: WARNING: undefined label: t3coreapi:database-query-helper-quotedatabaseidentifiers
./Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst:21: WARNING: undefined label: t3coreapi:database-query-helper-quotedatabaseidentifiers
./Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst:127: WARNING: …

[TASK] Resolve rendering warnings

---

Documentation/ColumnsConfig/Type/None/Properties/Size.rst

The cols property was removed with v12.0. Therefore, the sentence does not make sense anymore. It is removed.
Additionally, the directive was changed to "versionchanged" as the cols property was really removed and not only deprecated.
See also: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73816/2/typo3/sysext/backend/Classes/Form/Element/NoneElement.php
This also removes the warning while rendering:
./Documentation/ColumnsConfig/Type/None/Properties/Size.rst:14: WARNING: undefined label: columns-none-properties-cols

[TASK] Remove sentence about "cols" property in "none" type

---

Documentation/ColumnsConfig/Type/Datetime/Properties/Format.rst

See second note in the changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97232-NewTCATypeDatetime.html
This also removes the rendering warning:
./Documentation/ColumnsConfig/Type/Datetime/Properties/Format.rst:21: WARNING: undefined label: columns-datetime-properties-eval

[TASK] Adjust note in format property of datetime type

---

Documentation/Ctrl/Properties/Security.rst

The Configuration/TCA/table.php files return an array with the TCA definition. Therefore, the examples should reflect this.

[BUGFIX] Correct examples for $GLOBALS['TCA'][$table]['ctrl']['security']

---

Documentation/Ctrl/Properties/Security.rst

The Configuration/TCA/table.php files return an array with the TCA definition. Therefore, the examples should reflect this.

[Backport 11.5] [BUGFIX] Correct examples for $GLOBALS['TCA'][$table]['ctrl']['security'] (#712)

---

Documentation/Ctrl/Properties/FormattedLabelUserFunc.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/207
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/727

[TASK] Add note about outdated example for formattedLabel_userFunc

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst

resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/603

Follow naming conventions for tables on MM page

---

Documentation/ColumnsConfig/Type/Select/Tree/Index.rst

[ISSUE] Add description to selectTree #664
resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/664
releases: main
Remark: I have written a description for the selectTree

[ISSUE] Add description to selectTree #664

---

Documentation/ColumnsConfig/Type/Datetime/Properties/Format.rst

releases: main
Remark: I added "timesec", because it was missing, even tho it was written in the Changelog: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97232-NewTCATypeDatetime.html

[FIX] Adding missing information in the TCA for the datetime formats

---

Documentation/CodeSnippets/Manual/FlexformCheckbox2.rst.txt

Without the value tag the data are not persisted 
See https://forge.typo3.org/issues/101476#change-498187

[BUGFIX] Add value tag for checkbox FlexForm example

---

Documentation/ColumnsConfig/Type/Number/Properties/ValuePicker.rst

Fixed typo in ValuePicker example (https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Number/Properties/ValuePicker.html)
Forgot a "," at the end of the 'mode' => '' line.

Fixed typo in ValuePicker example

---

Documentation/Settings.cfg

Additionally, remove the outdated t3cheatsheets reference.
Releases: 12.4

[TASK] Adjust links to sysext manuals for v12.4

---

Documentation/BestPractises/LanguageFields.rst
Documentation/Ctrl/Properties/LanguageField.rst
Documentation/Settings.cfg

- Remove outdated t3cheatsheets reference
- Use t3translate instead of t3l10n like other manuals
- Add missing system extension manuals

[TASK] Streamline manual links

---

Documentation/BestPractises/LanguageFields.rst
Documentation/Ctrl/Properties/LanguageField.rst
Documentation/Settings.cfg

- Remove outdated t3cheatsheets reference
- Use t3translate instead of t3l10n like other manuals
- Add missing system extension manuals

[Backport 12.4] [TASK] Streamline manual links (#758)

---

Documentation/Introduction/Index.rst

Preport of #769
Ctrl has two main categories. mentioned three - Update Index.rst
It is confusing for the reader to see three points after mentioning that there are two main categories

[PREPORT] Ctrl has two main categories, but mentioned three 

---

Documentation/CodeSnippets/Checkbox17.rst.txt
Documentation/CodeSnippets/Checkbox18.rst.txt

The settings `labelChecked` and `labelUnchecked` are only used with render type `checkboxLabeledToggle` and misleading here.
See core for reference:
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaCheckboxItems.php#L86
The error exists also in older versions of the documentation. If desired, I can also create patches for these versions.

[BUGFIX] Fix wrong information in code snippets

---

Documentation/ColumnsConfig/CommonProperties/FieldInformation.rst

This just confused my co workers

Add example for fieldInformation and a hint to use description for default cases

---

Documentation/ColumnsConfig/Type/Text/Index.rst
Documentation/Settings.cfg

Also fixes an anchor to the "property enableRichtext". Additionally, add line breaks after 80 characters.

[TASK] Add links on "text" TCA type page

---

Documentation/ColumnsConfig/Type/Slug/Examples.rst
Documentation/ColumnsConfig/Type/Slug/Index.rst

The note is moved to the start page of the type to be consistent with the other types (which have sometimes no example page). Additionally, a link to more information about this in TYPO3 Explained is added.

[TASK] Move note about auto-generated slug db field

---

Documentation/Types/Properties/BitmaskExcludelistBits.rst
Documentation/Types/Properties/BitmaskValueField.rst
Documentation/Types/Properties/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/689
Releases: main

[TASK] #102108 - Remove obscure TCA [types][bitmask_*] settings

---

Documentation/ColumnsConfig/Type/Color/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/688
Releases: main

[FEATURE] #102107 - Auto-create DB fields from TCA columns for type "color"

---

Documentation/ColumnsConfig/Type/Password/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/687
Releases: main

[FEATURE] #102106 - Auto-create DB fields from TCA columns for type "password"

---

Documentation/ColumnsConfig/Type/Group/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/660
Releases: main

[FEATURE] #101908 - Auto-create DB fields from TCA columns for type "group"

---

Documentation/ColumnsConfig/Type/Language/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/655
Releases: main

[FEATURE] #101915 - Auto-create DB fields from TCA columns for type "language"

---

Documentation/ColumnsConfig/Type/ImageManipulation/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/652
Releases: main

[FEATURE] #101890 - Auto-create DB fields from TCA columns for type "imageManipulation"

---

Documentation/ColumnsConfig/Type/Check/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/647
Releases: main

[FEATURE] #101653 - Auto-create DB fields from TCA columns for type "check"

---

Documentation/ColumnsConfig/Type/Text/Index.rst
Documentation/Settings.cfg

Also fixes an anchor to the "property enableRichtext". Additionally, add line breaks after 80 characters.

[Backport 12.4] [TASK] Add links on "text" TCA type page (#804)

---

Documentation/ColumnsConfig/Type/Text/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/677
Releases: main

[FEATURE] #101986 - Auto-create DB fields from TCA columns for type "text"

---

Documentation/ColumnsConfig/Type/Flex/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/666
Releases: main

[FEATURE] #101997 - Auto-create DB fields from TCA columns for type "flex"

---

Documentation/ColumnsConfig/Type/Email/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/641
Releases: main

[FEATURE] #101654 - Auto-create DB fields from TCA columns for type "email"

---

Documentation/ColumnsConfig/Type/File/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/632
Releases: main

[FEATURE] #101553 - Auto-create DB fields from TCA columns for type "file"

---

Documentation/ColumnsConfig/Type/Category/Index.rst
Documentation/ColumnsConfig/Type/Datetime/Index.rst
Documentation/ColumnsConfig/Type/Uuid/Index.rst

Type "slug" has already this note, type "json" is not documented, yet.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Feature-101553-Auto-createDBFieldsFromTCAColumns.html#impact

[TASK] Add missing note about auto-created DB fields from TCA in v12

---

Documentation/ColumnsConfig/Type/Link/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/697
Releases: main

[FEATURE] #102163 - Auto-create DB fields from TCA columns for type "link"

---

Documentation/ColumnsConfig/Type/Radio/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/696
Releases: main

[FEATURE] #102163 - Auto-create DB fields from TCA columns for type "radio"

---

Documentation/ColumnsConfig/Type/Select/Tree/Index.rst

Now links are displayed correctly. Before a rendering warning occurred.

[BUGFIX] Correct indentation for toctree in Select/Tree

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/CommonProperties/Multiple.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/631
Releases: main

[TASK] #101554 - Remove MM_hasUidField

---

Documentation/ColumnsConfig/Type/Flex/AboutDataStructures.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParent.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParentSubField.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsTableField.rst

As the migration of the lookups can already be done in v12, a note is added to those configuration options.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/705
Releases: 12.4

[TASK] #102224 - Add note about removing FlexForm dataStructure lookups in v13

---

Documentation/ColumnsConfig/Type/File/Index.rst

This is needed to link from the "Using FAL" chapter in TYPO3 Explained to this section.

[TASK] Add anchor to "Migration" section of TCA type "file"

---

Documentation/ColumnsConfig/Type/Group/Index.rst

Usage of the quotes in PHP example code is inconsistent.

Add missing quote in PHP code

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

In some cases, this property was spelled with all-lowercase, which is not correct.

Fix spelling of allowNonIdValues

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

This property was sometimes spelled as all-lowercase.

Fix spelling of exclusiveKeys

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Properties/ExclusiveKeys.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst

The property exclusiveKeys is not available for all select types, it is only available for selectMultipleSideBySide and selectTree renderType (and category type).
The property is removed for the others and a note added.
The type category is left as is.
Resolves: #426

Remove exclusiveKeys property for some select renderTypes

---

Documentation/ColumnsConfig/Type/Input/ColorPicker/Index.rst
Documentation/ColumnsConfig/Type/Input/Default/Index.rst
Documentation/ColumnsConfig/Type/Input/Link/Index.rst

The input render types usually have common properties, but these are not listed on the renderType pages, there is not a link to the properties there, only on the parent page.
This is a patch specific to v11.5 to add a link to the common properties page to the input renderType pages. This is handled differently in the versions >= 11.5.
Resolves: #668

Show properties for renderTypes (v11.5 only)

---

Documentation/ColumnsConfig/Type/Select/Single/Properties.rst

_columns-select-properties-mm-match-fields: should not exist twice.
Resolves: #593

Remove duplicate label definition

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Properties/ExclusiveKeys.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst

The property exclusiveKeys is not available for all select types, it is only available for selectMultipleSideBySide and selectTree renderType.
The property is removed for the others and a note added.
The type category is left as is.
Resolves: #426

Remove exclusiveKeys property for some select renderTypes (#861)

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

The previous explanation for foreign_table_where was slightly misleading. The examples speak for themselves, but they are further down on the page.
The WHERE-clause is effectively appended to the existing WHERE clause created by TYPO3 using the default values and must start with AND.
Also, additional clauses such as ORDER BY or GROUP BY may be added after the WHERE-clause.
Resolves: #663

Clarify foreign_table_where

---

Documentation/ColumnsConfig/Type/Inline/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/704
Releases: main

[FEATURE] #102210 - Auto-create DB fields from TCA columns for type "inline"

---

Documentation/ColumnsConfig/Type/Number/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/710
Releases: main

[FEATURE] #102237 - Auto-create DB fields from TCA columns for type "number"

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

Can be backported in 12.4 and 11.5 where the typo also exists.

Fix missing backtick

---

Documentation/ColumnsConfig/Type/File/Index.rst

['jpg','png','svg'] causes: PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-backend/Classes/Form/FieldControl/ElementBrowser.php line 77

Update allowed image types

---

Documentation/ColumnsConfig/Type/File/Index.rst

['jpg','png','svg'] causes: PHP Warning: Array to string conversion in /var/www/html/vendor/typo3/cms-backend/Classes/Form/FieldControl/ElementBrowser.php line 77

Update allowed image types (#899)

---

.ddev/config.yaml
.github/workflows/tests.yml
.php-cs-fixer.dist.php
Build/Scripts/runTests.sh
composer.json

Also switch to php-cs-fixer directly, as typo3/coding-standards are not compatible with Symfony 7 by now. The fixer rules from Core are used.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/781
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/786
Releases: main

[TASK] Use PHP 8.2 and allow Symfony 7

---

Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
Documentation/ColumnsConfig/Type/Select/Properties/SortItems.rst

The 10.4 version hints are removed as all LTS versions now support these features.

[TASK] Remove old versionadded directives

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst
Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/776
Releases: main

[FEATURE] #95808 - Enable item groups for foreign_table for select type

---

Documentation/ColumnsConfig/Type/Category/Properties/ForeignTable.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTablePrefix.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableWhere.rst
Documentation/ColumnsConfig/Type/Category/Properties/Index.rst
Documentation/ColumnsConfig/Type/Category/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/ForeignTablePrefix.rst
Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

"foreign_table_where" is already available, the other properties were missing.

[BUGFIX] Add missing category properties around foreign_table

---

Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst

Rendering warning:
./Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst:30: CRITICAL: Unexpected section title.
Releases: main

[BUGFIX] Avoid rendering warning in DbFieldLength section

---

Documentation/ColumnsConfig/Type/File/Properties/Allowed.rst

This is not documented anywhere and didn't work as well when testing. The code for this is:
```
if (!empty(($allowed = ($fieldConfig['config']['allowed'] ?? null)))) {
$fieldConfig['config']['allowed'] = self::prepareFileExtensions($allowed);
}
```

[TASK] Remove wrong default for type `file` `allowed`

---

Documentation/ColumnsConfig/Type/Category/Properties/ForeignTable.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTablePrefix.rst
Documentation/ColumnsConfig/Type/Category/Properties/Index.rst
Documentation/ColumnsConfig/Type/Category/Properties/ItemGroups.rst
Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst

Additionally, "RenderType" for properties "foreign_table" and "foreign_table_prefix" have been removed as category has no render types. The toctree is also ordered alphabetically.

[TASK] Add missing itemGroups property to category type

---

Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableItemGroup.rst
Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst

Additionally, fix the confval value of the corresponding select property.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/776
Releases: main

[FEATURE] #95808 - Enable item groups for foreign_table for category type

---

Documentation/Ctrl/Properties/SearchFields.rst

Added uuid and json as valid field types. These were added in TYPO3 v12 and are available to be used in the live search.

Update list of valid searchable field types

---

Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst

type="select" is no longer allowed.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/836

[TASK] Add note about breaking flex form section change

---

Documentation/ColumnsConfig/Type/Check/Default.rst
Documentation/ColumnsConfig/Type/Check/Properties/RenderType.rst

The default value for `renderType` is always equivalent to the `type`. There does not exist a renderType with the value `default`. The actual default is the value `check`, the same as the type.

[TASK] Fix wrong default renderType for type check

---

Documentation/ColumnsConfig/Type/Datetime/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/728
Releases: main

[FEATURE] #99937 - Utilize BIGINT database column type for datetime TCA

---

Documentation/ColumnsConfig/Type/Datetime/Index.rst

See https://review.typo3.org/c/Packages/TYPO3.CMS/+/82992 for the mistake of this. My bad :-(
Follow-up due to #936

[TASK] Properly document TCA datetime default "bigint signed"

---

Documentation/Ctrl/Properties/VersioningWS.rst

t3ver_label was removed with TYPO3 10, see https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

Remove references to t3ver_label which was removed in v10

---

Documentation/ColumnsConfig/Type/Inline.rst

This option was removed with TYPO3v7, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/44363

[BUGFIX] Remove "showRemovedLocalizationRecords" from "inline" example (v10)

---

Documentation/ColumnsConfig/Type/Inline.rst

This option was removed with TYPO3v7, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/44363

[BUGFIX] Remove "showRemovedLocalizationRecords" from "inline" example (v9)

---

Documentation/ColumnsConfig/Properties/InlineAppearance.rst.txt

This option was removed with TYPO3v7, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/44363

[BUGFIX] Remove "showRemovedLocalizationRecords" from "inline" options (v8)

---

Documentation/ColumnsConfig/Type/Inline.rst

This option was removed with TYPO3v7, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/44363

[BUGFIX] Remove "showRemovedLocalizationRecords" from "inline" example (v8)

---

Documentation/ColumnsConfig/Type/Folder/Index.rst
Documentation/ColumnsConfig/Type/Folder/Properties/ElementBrowserEntryPoints.rst
Documentation/ColumnsConfig/Type/Folder/Properties/FieldControl.rst
Documentation/ColumnsConfig/Type/Folder/Properties/Index.rst

[TASK] Overhaul folder type

---

Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst

Since https://review.typo3.org/c/Packages/TYPO3.CMS/+/82240 the effectivePid and site are passed to the itemsProcFunc

[TASK] Add effectivePid and site to itemsProcFunc parameters

---

Documentation/Ctrl/Properties/TranslationSource.rst

Replaces "l10n_parent" with "l10n_source" in the convention hint of 'ctrl'-property 'translationSource'

Fix incorrect field name in 'translationSource'

---

Documentation/CodeSnippets/Manual/Ctrl/Language.rst.txt
Documentation/ColumnsConfig/Type/Passthrough/Index.rst
Documentation/Ctrl/Properties/TranslationSource.rst

As mentioned several times throughout the TCA documentation, l10n_ should be used by convention, and l18n_ must be kept for some core tables for historic reasons. l10n_ should therefore be used consistently, except when explaining those historic reasons.

Consistent use of l10n_ as prefix for all localization fields

---

Documentation/Ctrl/Properties/GroupName.rst

It's the third time now that I stumbled over the problem, that in create new record wizard the icon of my group is from a foreign extension. This time it was the icon of tx_scheduler, which has nothing to do with my extension. TYPO3 tries to find a loaded extension by the second part of the tablename. This is OK for all extensions without underscore. But with underscore the second part of table name does not match any extension key. That's why it comes to these side-effects. Easiest solution is to enter a localized title. In that case the extension key will be extracted from the LLL:EXT: path. Else you should set groupName to your extension key. That way an extension can be found and the correct group icon (ext icon) will be shown again

Add info about wrong icon usage

---

Documentation/BestPractises/Index.rst

Updated spelling, see
https://www.scribbr.com/us-vs-uk/practise-or-practice/ for details.
"to practise is only a verb in UK, in US it is never used"

Update Index.rst, fixed spelling

---

Documentation/Ctrl/Properties/VersioningWS.rst
Documentation/Ctrl/Properties/VersioningWSAlwaysAllowLiveEdit.rst

Some of the mentioned fields on this page don't exist anymore: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Ctrl/Properties/VersioningWS.html
t3ver_id
t3ver_label
t3ver_move_id
Expected behavior/output
To have that section reflect to current way of how records in workspaces are actually handled.
TYPO3 versions
11+
Fields are gone since 10 and 11:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-88143-Version-relatedDatabaseFieldT3ver_idRemoved.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-92497-WorkspacesMovePlaceholdersRemoved.html
resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/i …

[TASK] Rework workspace docs

---

Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst

Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/841 Releases: main

[TASK] Add link to changelog for deprecated flex form section usage

---

Documentation/ColumnsConfig/Type/Input/_Properties/_Max.rst.txt

[BUGFIX] Avoid new paragraph in note for input's "max"

---

Documentation/ColumnsConfig/Type/Link/_Snippets/_SomeService.php

The given example does not make much sense if nothing besides the URL/URI is used from a link

Prefer LinkFactory::createUri() for pure URI creation

---

Documentation/ColumnsConfig/Type/Flex/AboutDataStructures.rst
Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst

Remove further mentioning of the list_type not covered by #1182
Reference: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1071
Releases: main

[TASK] Deprecate plugin content element and plugin subtypes (list_type)

---

Documentation/ColumnsConfig/Type/Datetime/_Properties/_Nullable.rst.txt

See: 87294: [BUGFIX] Remove inconvenient nullable checkbox from datetime elements | https://review.typo3.org/c/Packages/TYPO3.CMS/+/87294

Update description of DateTime nullable option

---

Documentation/ColumnsConfig/Type/None/_Properties/_Format.rst.txt

fix: format code block for none type correctly

---

Documentation/ColumnsConfig/Type/Link/_Properties/_Appearance.rst.txt

[BUGFIX] For TCA type=link the TCA option is allowedFileExtensions

---

Documentation/ColumnsConfig/Type/Datetime/_Properties/_Nullable.rst.txt

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1226
Releases: main, 13.4

[BUGFIX] Treat 0 as a defined value for nullable datetime fields

---

Documentation/ColumnsConfig/Type/Color/_Properties/_ValuePicker.php
Documentation/ColumnsConfig/Type/Color/_Properties/_ValuePicker.rst.txt
Documentation/ColumnsConfig/Type/Input/_Properties/_ValuePicker.rst.txt
Documentation/ColumnsConfig/Type/Link/_Properties/_ValuePicker.rst.txt
Documentation/ColumnsConfig/Type/Link/_Snippets/_valuePicker.php
Documentation/ColumnsConfig/Type/Number/_Properties/_ValuePicker.php

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1222
Releases: main

[FEATURE] Associative array keys for TCA valuePicker items

---

Documentation/Types/_Properties/_ColumnsOverrides.rst.txt

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1022

[BUGFIX] Migrate allowLanguageSynchronization in columnsOverrides

---

Documentation/ColumnsConfig/CommonProperties/FieldInformation.rst

The description in docs CoreAPI tells something different as written here. It say that all these three extending features are implemented for nearly all form fields. I have updated that part here and repaired the defect :ref: link

Update hint about TCA:fieldInformation

---

Documentation/ColumnsConfig/Type/Group/_Properties/_ForeignTable.rst.txt

Patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/88898 was merged and release in 13.4.10. This makes the option obsolete, unless BC is needed.

[TASK] Drop "foreign_table" TCA extbase requirement on type=group

---

Documentation/ColumnsConfig/Type/User/Index.rst

See https://forge.typo3.org/issues/106875#change-544592
The current docs do not mention that DI (Services.yaml with at least a minimal configuration) needs to be used.

Add a note about DI in custom form inputs
