TYPO3-Documentation/TYPO3CMS-Reference-TCA

Documentation/Reference/Ctrl/Index.rst

adds the description for the new setting descriptionColumn for section crtl in TCA
(Feature: #67603)

[TASK] description for new crtl.descriptionColumn

---

Documentation/Reference/Columns/Inline/Index.rst

[BUGFIX] Document default value of enableDiscadingDelete

---

Documentation/AdditionalFeatures/CoreWizardScripts/Index.rst

See 
https://forge.typo3.org/issues/70602
Please backport this to 7.6

Change wizard_element_browser to wizard_link

---

Documentation/AdditionalFeatures/WizardsConfiguration/Index.rst

fix icon file path

---

Documentation/Reference/Columns/Input/Index.rst

Provides an example evaluation using namespaces

Update example for namespaced evaluation classes

---

Documentation/AdditionalFeatures/CoreWizardScripts/Index.rst
Documentation/AdditionalFeatures/WizardsConfiguration/Index.rst
Documentation/Reference/Columns/Check/Index.rst

- #77592 - Dropped TCA option showIfRTE in type=check
- #77630 - Remove wizard icons

WIP [TASK] Update documentation for changes in 8.4

---

Documentation/Reference/Ctrl/Index.rst

chanegs following https://review.typo3.org/#/c/50462/

Remove not used versioning_followPages and change versioningWS

---

Documentation/Reference/Ctrl/Index.rst

resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/84

update shadowColumnsForMovePlaceholders description

---

Documentation/AdditionalFeatures/WizardsConfiguration/Index.rst

Add the missing documentation of maxItemsInResultList, which has always been available.

Add maxItemsInResultList for SuggestWizard

---

Documentation/Reference/Columns/Select/Index.rst

It was unclear, i thought you need the [ ] cling squares and my code failed with errors beacuse of this.

Improved example of foreign_table_where

---

Documentation/ColumnsConfig/Properties/CommonFieldControl.rst

Add a little hint were to find configuration examples for fieldControl.

Point to Configuration Examples

---

Documentation/ColumnsConfig/Properties/InputDbType.rst

FIX php syntax error Update InputDbType.rst

---

Documentation/ColumnsConfig/Type/Flex.rst

And the selection of "$GLOBALS['TCA']" is required.

add position where to find the "pi_flexform"

---

Documentation/ColumnsConfig/Behaviour/AllowLanguageSynchronization.rst
Documentation/ColumnsConfig/Behaviour/CommonAllowLanguageSynchronization.rst
Documentation/ColumnsConfig/Properties/CheckRenderType.rst
Documentation/ColumnsConfig/Properties/CommonRenderTypeDefault.rst
Documentation/ColumnsConfig/Properties/SelectRenderType.rst
Documentation/ColumnsConfig/Type/Check.rst
Documentation/ColumnsConfig/Type/Flex.rst
Documentation/ColumnsConfig/Type/Group.rst
Documentation/ColumnsConfig/Type/ImageManipulation.rst
Documentation/ColumnsConfig/Type/Inline.rst
Documentation/ColumnsConfig/Type/Input.rst
Documentation/ColumnsConfig/Type/None.rst
Documentation/ColumnsConfig/Type/Passthrough.rst
Documentation/ColumnsConfig/Type/Radio.rst
Documentation/ColumnsConfig/Type/Select.rst
Documentation/ColumnsConfig/Type/Text.rst
Documentation/ColumnsConfig/Type/User.rst

- Fix some errors with error section levels
- Document new renderTypes
- Fix orphaned AllowLanguageSynchronization
Fixes: #181
Fixes: #179
Fixes: #178
Fixes: #176

Document new renderTypes and fix some other issues

---

Documentation/ColumnsConfig/Properties/GroupAllowed.rst.txt
Documentation/ColumnsConfig/Type/Group.rst

- add missing closing backtick
- wrap lines
- link allowed property

Nitpicks in group field description

---

Documentation/Palettes/Index.rst
Documentation/Palettes/PalettesLabel.rst.txt

See typo3/sysext/core/Documentation/Changelog/9.0/Feature-82826-TCAAllowLabelInPalettesArray.rst

[TASK] Document palettes label field

---

Documentation/ColumnsConfig/Type/Slug.rst

* fix missing comma
* add full TCA example

[TASK] Fix slug configuration example

---

Documentation/AdditionalFeatures/CoreWizardScripts/Index.rst

Added example for link wizard configuration with `blindLinkOptions`

Add example for link wizard configuration with blindLinkOptions

---

Documentation/ColumnsConfig/Properties/SlugPrependSlash.rst.txt
Documentation/ColumnsConfig/Type/Slug.rst

see typo3/sysext/core/Documentation/Changelog/9.5/Feature-86457-TCATypeSlugAddsAPrependingSlash.rst

[TASK] Document slug property prependSlash

---

Documentation/Ctrl/CtrlLabel.rst.txt

Please find a more detailed description at the following issue on forge:
https://forge.typo3.org/issues/87041

Add warning to use input/text fields for label

---

Documentation/ColumnsConfig/Properties/SlugGeneratorOptions.rst.txt

See also review for changelog: https://review.typo3.org/c/59455/

[BUGFIX] Fix code snippet for slug

---

Documentation/ColumnsConfig/Type/Inline.rst

Replace LLL:EXT:cms/locallang_ttc.xlf with LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf

Fix non existing language label

---

Documentation/Ctrl/CtrlTypeiconColumn.rst.txt

Fixes tiny type in te description.

Fix tiny typo in CtrlTypeiconColumn.rst.txt

---

Documentation/ColumnsConfig/Properties/ImageManipulationCropVariants.rst.txt

The core extension lang isn't available anymore, the labels moved to the core extension

Change LLL:EXT:lang to LLL:EXT:core

---

Documentation/ColumnsConfig/Type/Flex.rst

See example:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/DataFormats/T3datastructure/SheetReferences/Index.html

<sheets> instead of <sheet>

---

Documentation/ColumnsConfig/Type/Check.rst

renderType checkboxToggle does not support labelChecked or labelUnchecked.

Update renderType checkboxToggle

---

Documentation/ColumnsConfig/Type/Slug.rst

'default' => ''
to support the Mysql strict mode
see file /sysext/core/Configuration/TCA/pages.php

add default

---

Documentation/ColumnsConfig/Properties/GroupSuggestOptions.rst.txt

`TYPO3\\CMS\\Backend\\Form\\Wizard\\SuggestWizardDefaultReceiver` instead of `TYPO3\\CMS\\Backend\\Form\\WizardSuggestWizardDefaultReceiver`.

Fix SuggestWizardDefaultReceiver class path

---

Documentation/ColumnsConfig/Type/Check.rst

- do not indent text: will result in "quote" style with new theme
- add subheaders for examples

Fix example for type check

---

Documentation/ColumnsConfig/Properties/InputDbType.rst.txt

see https://forge.typo3.org/issues/88712

Add eval null to make it work for mysql strict mode

---

Documentation/ColumnsConfig/Properties/SlugEval.rst.txt

@helhum can you proof read that, thx

[TASK] Improve slug eval options

---

Documentation/Ctrl/CtrlSeliconField.rst.txt

Mention FAL requirement for "selicon_field"

---

Documentation/ColumnsConfig/Introduction/Index.rst

Add a short sentence that explains where including a file reference is documented.

Mention where to include file references

---

Documentation/Ctrl/CtrlUseColumnsForDefaultValues.rst.txt

Resolves: #271
Releases: master, 10.4, 9.5

Add explanation for useColumnsForDefaultValues

---

Documentation/Ctrl/CtrlFormattedLabelUserFunc.rst.txt
Documentation/Ctrl/CtrlFormattedLabelUserFuncOptions.rst.txt

[TASK] Enhance section about formattedLabel_userFunc

---

Documentation/Columns/ColumnsDisplayCond.rst.txt

Additionally, fix the indentation to 3 spaces.

[TASK] Avoid visual quote style in displayCond section

---

Documentation/ColumnsConfig/Type/ImageManipulation.rst
Documentation/ColumnsConfig/Type/Inline.rst
Documentation/Ctrl/Index.rst

[TASK] Replace EXT:lang reference

---

Documentation/ColumnsConfig/Type/selectSingle.rst

See Feature 89032
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845

[FEATURE] Add fieldControl to selectSingle

---

Documentation/Ctrl/CtrlVersioningWS.rst.txt

See Core Breaking 89137
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
Releases: 11.0

[TASK] Remove t3ver_tstamp & t3ver_count

---

Documentation/ColumnsConfig/Type/Inline.rst

Make it more clear that enableCascadingDelete and disableMovingChildrenWithParent belong to behaviour

[TASK] Improvement of behaviour properties

---

Documentation/ColumnsConfig/Properties/SelectCheckBoxAppearance.rst.txt
Documentation/ColumnsConfig/Type/selectCheckBox.rst

See Core Feature 91859
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082

[FEATURE] expandAll for selectCheckBox

---

Documentation/Index.rst

See https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/187

Fix invalid links to Forger

---

Documentation/ColumnsConfig/Type/inputDateTime.rst
Documentation/Ctrl/CtrlSearchFields.rst.txt

Mention fields that are excluded from LiveSearch by default
Closes #325

Add note about excluded search fields

---

Documentation/ColumnsConfig/Type/User.rst

[TASK] Make a propper deprecation note for type=user with property

---

Documentation/ColumnsConfig/Properties/SlugEval.rst.txt

Add a hint to prevent using uniqueInSite within a multi-domain setup.

Add unique as eval keyword

---

Documentation/ColumnsConfig/Type/User/Index.rst

broken output

---

Documentation/ColumnsConfig/Type/User/Index.rst

Reverts TYPO3-Documentation/TYPO3CMS-Reference-TCA#353
It still does not work.

Fix "attention box"

---

Documentation/ColumnsConfig/Type/Input/DateTime/Properties/Eval.rst

Fix indentation and line length

---

Documentation/Types/Properties/SubtypesExcludelist.rst

Add information about removing additional fields from Form for plugins (subtypes_excludelist)
refs #290

[Feature] subtypes_excludelist example

---

Documentation/Columns/Properties/L10nMode.rst

[BUGFIX] Fix including snippet

---

Documentation/ColumnsConfig/Type/Group/Properties/FieldWizard.rst

- Fix indentation which causes blockquotes
- spelling

[TASK] Fix Group FieldWizard

---

Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst

- List all available parameters
- Replace flex with select in types
- Use the term method instead of function
- Use a styleguide example instead of a (more complex) core example
- Small text fixes

[TASK] Improve ItemsProcFunc documentation

---

Documentation/ColumnsConfig/Type/Passthrough/Index.rst

php classes

---

Documentation/Ctrl/Properties/Label.rst

also the label field is shown

---

Documentation/ColumnsConfig/Type/Select/Properties/Items.rst

- Use auto-incrementing numbered list.
- Fix unintended blockquote.
- Use inline code format instead of quotes.

[BUGFIX] Fix formatting in Items.rst

---

Documentation/Ctrl/CtrlLabelAltForce.rst.txt

the label is also shown

---

Documentation/Introduction/Index.rst

Merge only when repository has been renamed.
See https://github.com/TYPO3-Documentation/TYPO3CMS-Code-Examples/issues/31

[TASK] Rename repository to TYPO3-Documentation/t3docs-examples

---

Documentation/CodeSnippets/Inline1nInline1.rst.txt
Documentation/CodeSnippets/InlineFalInline1Flexform.rst.txt
Documentation/CodeSnippets/InlineMmChildParents.rst.txt
Documentation/CodeSnippets/InlineMmInline1.rst.txt
Documentation/CodeSnippets/InlineMnChildParents.rst.txt
Documentation/CodeSnippets/InlineMnInline1.rst.txt
Documentation/CodeSnippets/InlineMnSymetricBranches.rst.txt
Documentation/CodeSnippets/InlineMnSymetricInline1.rst.txt
Documentation/CodeSnippets/Manual/FileFieldTCAConfig.rst.txt
Documentation/CodeSnippets/Manual/InlineMnSymetricMm.rst.txt
Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst

This TCA option is not used by the core since v7 anymore.

[TASK] Remove all showRemovedLocalizationRecords occurrences

---

Documentation/Columns/ColumnsDisplayCond.rst.txt

Backport of #415 for 10.4 branch

[BUGFIX] Replace semicolon by comma

---

Documentation/ColumnsConfig/Type/Select/Properties/FileFolderConfig.rst

related to https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/181

[FEATURE]  #94406 - Override fileFolder TCA configuration with TSconfig

---

Documentation/Columns/Properties/DisplayCond.rst

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.

[TASK] Update TYPO3 repository URL

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
See Core Feature 94662

[FEATURE] Access site configuration in foreign_table_where

---

Documentation/CodeSnippets/Manual/CategoryFlexform.rst.txt
Documentation/CodeSnippets/Manual/CategoryOneTo.rst.txt
Documentation/CodeSnippets/Manual/CategorySimple.rst.txt
Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Index.rst
Documentation/ColumnsConfig/Type/Category/Examples.rst
Documentation/ColumnsConfig/Type/Category/Index.rst
Documentation/ColumnsConfig/Type/Category/Properties/Default.rst
Documentation/ColumnsConfig/Type/Category/Properties/ExclusiveKeys.rst
Documentation/ColumnsConfig/Type/Category/Properties/Index.rst
Documentation/ColumnsConfig/Type/Category/Properties/Relationship.rst
Documentation/ColumnsConfig/Type/Category/Properties/TreeConfig.rst

[Feature] #94622 - New TCA type “category”

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/CommonProperties/Multiple.rst
Documentation/ColumnsConfig/Type/Group/Properties/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Properties/ForeignTable.rst
Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95061-AutoCreationOfMMTablesFromTCA.html

[Feature] #95061 - Auto creation of MM tables from TCA

---

Documentation/ColumnsConfig/Type/Category/Properties/TreeConfig.rst
Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95037-NewStartingPointsSettingForFormEngineTreeConfig.html

[Feature] #95037 - New startingPoints setting for FormEngine treeConfig

---

Documentation/ColumnsConfig/Type/Category/Properties/TreeConfig.rst
Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
See 95037

[TASK] Deprecate rootUid for Trees

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

Dash does not exists in TCA config properties

Replace dash with underscore

---

Documentation/screenshots.json

releases: master, 11.5
ref https://github.com/TYPO3-Documentation/t3docs-screenshots/issues/227

[TASK] Remove goToTable from screenshots.json

---

Documentation/Columns/Properties/L10nMode.rst
Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst
Documentation/ColumnsConfig/Type/Group/Properties/Index.rst
Documentation/ColumnsConfig/Type/Input/Default/Examples.rst
Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
Documentation/ColumnsConfig/Type/Select/Properties/Items.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Text/Properties/RichtextConfiguration.rst
Documentation/ColumnsConfig/Type/User/Index.rst
Documentation/Ctrl/Properties/AdminOnly.rst
Documentation/Ctrl/Properties/VersioningWS.rst

[TASK] Fix warnings

---

Documentation/CodeSnippets/Manual/CheckboxDefault.rst.txt
Documentation/ColumnsConfig/Type/Check/Properties/Default.rst

Use manual code snippet for checkbox default value

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSortby.rst

[BUGFIX] Invalid MM related TCA 'sorting' and 'sorting_foreign'

---

Documentation/ColumnsConfig/Type/Category/Properties/Relationship.rst
Documentation/ColumnsConfig/Type/Check/Properties/Index.rst

This fixes some unintended blockquotes.

[BUGFIX] Remove unintended blockquotes

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst

Example TCA for mm table in group

---

Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst

move reference to non-deprecated property

---

Documentation/Reference/Columns/Input/Index.rst

See TYPO3-Documentation/T3DocTeam#165 for details.

[TASK] Unify top-level domain of dummy urls

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

See https://forge.typo3.org/issues/96065 for reference, where this led to issues.

Adjust information regarding quoting of ORDER BY and GROUP BY

---

.editorconfig
Documentation/ColumnsConfig/Type/Slug/Introduction.rst
Documentation/Index.rst

See TYPO3-Documentation/T3DocTeam#166 for details.

[TASK] Unify placeholder syntax

---

Documentation/ColumnsConfig/Type/Group/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/FieldControl.rst
Documentation/ColumnsConfig/Type/Group/Properties/Index.rst

In addition, fix some ref pointers.

[TASK] Rename mixed up property name for type group

---

Documentation/ColumnsConfig/Type/Input/Properties/ValuePicker.rst

[BUGFIX] Fix blockquote in value picker code example

---

Documentation/ColumnsConfig/Type/Input/DateTime/Properties/DbType.rst
Documentation/ColumnsConfig/Type/Input/DateTime/Properties/DisableAgeDisplay.rst
Documentation/ColumnsConfig/Type/Input/DateTime/Properties/Format.rst
Documentation/ColumnsConfig/Type/Input/DateTime/Properties/Range.rst

[BUGFIX] Fix blockquotes in datetime properties

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst

[BUGFIX] Fix typos in group MM documentation

---

Documentation/ColumnsConfig/Type/Input/Properties/ValuePicker.rst

releases: 11.5
is already fixed in main

Fix indentation

---

Documentation/ColumnsConfig/Type/Slug/Properties/FallbackCharacter.rst

[TASK] Add default value for slug fallbackCharacter

---

Documentation/ColumnsConfig/Type/Group/Properties/ElementBrowserEntryPoints.rst
Documentation/ColumnsConfig/Type/Group/Properties/Index.rst

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-91077-ElementBrowserEntryPointsForTCATypeGroup.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: main

Feature: #91077 - Element browser entry points for TCA type “group”

---

Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst
Documentation/Ctrl/Properties/UseColumnsForDefaultValues.rst

as the original still exists.
See https://english.stackexchange.com/questions/88400/when-to-use-override-and-overwrite
releases: main, 11.5

Override not overwrite configuration values

---

Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourDisableMovingChildrenWithParent.rst
Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourEnableCascadingDelete.rst

[BUGFIX] Fix path for behaviour properties

---

Documentation/ColumnsConfig/Type/Inline/Properties/ForeignTableField.rst

[BUGFIX] Add missing space

---

Documentation/ColumnsConfig/Type/Inline/Properties/ShowNewRecordLink.rst

[BUGFIX] Add the correct path for showNewRecordLink

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTablePrefix.rst

[BUGFIX] Fix header level

---

Documentation/ColumnsConfig/Index.rst
Documentation/ColumnsConfig/Type/Folder/Index.rst
Documentation/ColumnsConfig/Type/Folder/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Folder/Properties/ElementBrowserEntryPoints.rst
Documentation/ColumnsConfig/Type/Folder/Properties/FieldControl.rst
Documentation/ColumnsConfig/Type/Folder/Properties/HideMoveIcons.rst
Documentation/ColumnsConfig/Type/Folder/Properties/Index.rst
Documentation/ColumnsConfig/Type/Group/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/InternalType.rst

releases: main only!
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96983-TCATypeFolder.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

[Feature] TCA type "folder"

---

Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSelector.rst

add hint for mm table

---

Documentation/ColumnsConfig/Type/Group/Properties/Filter.rst

Forge ticket: https://forge.typo3.org/issues/93582

[TASK] Clarify filtered values for group filter option

---

Documentation/ColumnsConfig/Type/Input/DateTime/Properties/Eval.rst

[TASK] Add reference to inputDateTime eval options

---

Documentation/ColumnsConfig/CommonProperties/Multiple.rst

[TASK] Fix typo in multiple page

---

Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst

[BUGFIX] Fix reference link

---

Documentation/ColumnsConfig/Type/Select/Properties/AuthMode.rst
Documentation/ColumnsConfig/Type/Select/Properties/AuthModeEnforce.rst
Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
Documentation/ColumnsConfig/Type/Select/Properties/Items.rst

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97265-SimplifiedAccessModeSystem.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

[BREAKING] Breaking: #97265 - Simplified access mode system

---

Documentation/ColumnsConfig/Type/Email/Index.rst
Documentation/ColumnsConfig/Type/Email/Properties/Autocomplete.rst
Documentation/ColumnsConfig/Type/Email/Properties/Eval.rst
Documentation/ColumnsConfig/Type/Email/Properties/Index.rst
Documentation/ColumnsConfig/Type/Email/Properties/Size.rst
Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97013-NewTCATypeEmail.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

[Feature] #97013 - New TCA type “email”

---

Documentation/ColumnsConfig/Type/Link/Index.rst
Documentation/ColumnsConfig/Type/Link/Properties/AllowedTypes.rst
Documentation/ColumnsConfig/Type/Link/Properties/Appearance.rst

- Add missing allowedTypes options
- Fix misinterpreted record option
- Document all options in appearance
Releases: main

[TASK] Document missing options of type link

---

Documentation/BestPractises/LanguageFields.rst

Fix definition list syntax

---

Documentation/BestPractises/CommonFields.rst

It is already fixed in main with PR #621.

[BUGFIX] Fix link to DataHandler und reference to origUid

---

Documentation/ColumnsConfig/Type/Input/Properties/Min.rst
Documentation/ColumnsConfig/Type/Text/Properties/Index.rst
Documentation/ColumnsConfig/Type/Text/Properties/Min.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/143

[FEATURE] #92861 - Introduce TCA option "min"

---

Documentation/BestPractises/CommonFields.rst

Mandatory fields are actually created automatically

---

.ddev/config.yaml
.gitignore
composer.json

No more special project is needed

Generate Codesnippets directly from the repository

---

Documentation/Ctrl/Properties/Enablecolumns.rst
Documentation/Settings.cfg

[TASK] Remove references to the Extbase Book

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

[BUGFIX] Avoid masking underscore in directives

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

[Backport 11.5] [BUGFIX] Avoid masking underscore in directives (#644)

---

Documentation/ColumnsConfig/Type/Select/Index.rst

[TASK] Remove old note about change in version 7.6

---

Documentation/ColumnsConfig/Type/Slug/Examples.rst
Documentation/ColumnsConfig/Type/Slug/Introduction.rst

Additionally, add an explanation to the examples.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/199

[FEATURE] #97173 - Auto creation of database fields for TCA "slug"

---

Documentation/Ctrl/Properties/RootLevel.rst
Documentation/Ctrl/Properties/Security.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/208

[FEATURE] #98487 - Add TCA option [ctrl][security][ignorePageTypeRestriction]

---

Documentation/ColumnsConfig/Type/Category/Properties/Relationship.rst

Already fixed in main
releases: 11.5

Fix quote-style

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

In main branch the references are already available.
Releases: 11.5

[TASK] Reference PAGE_TSCONFIG_* markers

---

Documentation/CodeSnippets/Manual/CategoryFlexform.rst.txt
Documentation/CodeSnippets/Manual/FlexRte1.rst.txt
Documentation/CodeSnippets/Manual/FlexformCheckbox2.rst.txt
Documentation/ColumnsConfig/Type/Flex/Examples.rst
Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst
Documentation/ColumnsConfig/Type/Flex/Properties/Ds.rst

reverences https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/190

Remove "TCEforms" wrapper in FlexForm definitions

---

Documentation/Columns/Properties/DisplayCond.rst

[TASK] Remove old "versionchanged" information

---

Documentation/ColumnsConfig/Type/Group/Properties/Appearance.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/292
Releases: main

[TASK] #98479 - Appearance options in group type not evaluated anymore

---

Documentation/ColumnsConfig/Type/User/Index.rst
Documentation/ColumnsConfig/Type/User/_includes/_SpecialFieldElement.php
Documentation/ColumnsConfig/Type/User/_includes/_fe_users.php

In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/277

[TASK] Refactor type "user"

---

Documentation/ColumnsConfig/CommonProperties/ReadOnly.rst

add fieldtypes that accept parameter 'readonly'

---

Documentation/ColumnsConfig/CommonProperties/ReadOnly.rst

manual backport  of #687 for #431

Update ReadOnly.rst 

---

Documentation/ColumnsConfig/Type/Uuid/Index.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/EnableCopyToClipboard.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/Index.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/Size.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/Version.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/391
Releases: main

[FEATURE] #100171 - Introduce TCA type uuid

---

Documentation/ColumnsConfig/Type/Password/Index.rst
Documentation/ColumnsConfig/Type/Password/Properties/PasswordPolicy.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/410
Releases: main

[FEATURE] #97389 - Add password policy validation for TCA type=password

---

Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/406
Releases: main

[FEATURE] #65020 - Change button labels within TCA type=file

---

Documentation/Ctrl/Properties/DefaultSortby.rst

Also using the date makes more sense then sorting by bodytext...
releases: main, 11.5

Also give an example for DESC

---

Documentation/ColumnsConfig/Type/Link/Properties/Appearance.rst

It is annoying to add more content to a page which has the old indentation. This patch is a preparation for adding content for a new feature.
Releases: main

[TASK] Adjust indentation of type "link" > "appearance"

---

Documentation/ColumnsConfig/Type/Link/Properties/Appearance.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/418
Releases: main

[FEATURE] #84594 - Add additional parameters to email links

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/432
Releases: main

[TASK] #100335 - Deprecate TCA config MM_insert_fields

---

Documentation/ColumnsConfig/Type/File/Index.rst

[BUGFIX] Correct introduction for TCA type "file"

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/497
Releases: main

[TASK] #101009 - Remove TCA config MM_insert_fields

---

Documentation/ColumnsConfig/Type/Text/Index.rst

Point at where to learn more about the editor types

---

Documentation/ColumnsConfig/Type/Number/Properties/ValuePicker.rst

Fixed typo in ValuePicker example (#752)

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Documentation/Settings.cfg

[TASK] Streamline MM sections

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Documentation/Settings.cfg

[Backport 12.4] [TASK] Streamline MM sections (#755)

---

Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Documentation/Settings.cfg

[Backport 11.5] [TASK] Streamline MM sections (#755)

---

Documentation/Introduction/Index.rst

It is confusing for the reader to see three points after mentioning that there are two main categories

Ctrl has two main categories, but mentioned three - Update Index.rst

---

Documentation/ColumnsConfig/Type/Language/History.rst

[TASK] Fix spelling in language history

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

See https://github.com/TYPO3/typo3/blob/bf477e60fe53d0d7641834f2fed6fca1a6766087/typo3/sysext/backend/Classes/Form/FormDataProvider/AbstractItemProvider.php#L769

Use proper "quoted" term for PAGE_TSCONFIG_STR

---

Documentation/ColumnsConfig/Type/Flex/Index.rst

Additionally, add line breaks after 80 characters.

[TASK] Add link to FlexForms description on FlexForm page

---

Documentation/ColumnsConfig/Type/Folder/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/648
Releases: main

[FEATURE] #101890 - Auto-create DB fields from TCA columns for type "folder"

---

Documentation/ColumnsConfig/Type/Json/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/381

[TASK] Add stub for new TCA type "json"

---

Documentation/ColumnsConfig/CommonProperties/Mm.rst

[BUGFIX] Correct usage of :file: in MM section

---

Documentation/ColumnsConfig/Type/Color/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/650
Releases: main

[FEATURE] #101843 - Allow configuration of color palettes

---

Documentation/Ctrl/Properties/Index.rst
Documentation/Ctrl/Properties/PreviewRenderer.rst

Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-78450-IntroducePreviewRendererPattern.html
Resolves: #781

[FEATURE] Add preview renderer (#833)

---

Documentation/Ctrl/Properties/Index.rst
Documentation/Ctrl/Properties/PreviewRenderer.rst

Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-78450-IntroducePreviewRendererPattern.html
Resolves: #781

[Backport 11.5] [FEATURE] Add preview renderer (#833)

---

Documentation/ColumnsConfig/Type/Text/Properties/RichtextConfiguration.rst

The richtextConfiguration preset can be overridden via Page TSconfig RTE.
Add this information and add a link.

Refer to TSconfig config for richtextConfiguration

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

Add itemGroup property to list of select properties

---

Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst

Remove required from Eval options

---

Documentation/ColumnsConfig/Type/Input/Index.rst

This makes them better readable than previously.

[TASK] Adjust deprecation of TCA type "input"

---

Documentation/ColumnsConfig/CommonProperties/FieldInformation.rst

Add snippet in ext_localconf.php for custom FieldInformation

---

Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Index.rst
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst
Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/769
Releases: main

[FEATURE] #102279 - Auto create DB fields from TCA for type "select"

---

Documentation/ColumnsConfig/Type/Link/Index.rst

nullable only works with true/false not with single quotes

Fix nullable example

---

Documentation/ColumnsConfig/Type/Link/Index.rst

nullable only works with true/false not with single quotes

Fix nullable example (#912)

---

Documentation/ColumnsConfig/CommonProperties/FieldWizard/OtherLanguageContent.rst

see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/418#pullrequestreview-1835969611

[TASK] Break up "page/userTSconfig" as two words

---

Documentation/ColumnsConfig/Type/Password/Properties/Autocomplete.rst

[BUGFIX] Adjust highlighted line in autocomplete property of password type

---

Documentation/ColumnsConfig/Type/File/Index.rst

[BUGFIX] Correct reference in "file" type

---

Documentation/Types/Properties/Showitem.rst

Fix typo in previous commit

---

Documentation/ColumnsConfig/Type/Password/Properties/PasswordGenerator.rst
Documentation/Settings.cfg

In preparation for switch to PHP-based rendering

[TASK] Replace Sphinxobjects with confval

---

Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Flex/Index.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParent.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParentSubField.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsTableField.rst
Documentation/ColumnsConfig/Type/Inline/Examples.rst
Documentation/ColumnsConfig/Type/Password/Properties/PasswordPolicy.rst
Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst

Preparation for switch to PHP-based rendering
The guides are more strict in using interlinks then sphinx

[BUGFIX] Fix references

---

Documentation/guides.xml

I already fixed this in the backports.

[BUGFIX] add interlink shortcode

---

Documentation/ColumnsConfig/Type/Text/Properties/Nullable.rst

I hope this is more understandable.

change wording for Nullable TCA Config

---

Documentation/ColumnsConfig/Type/Inline/Properties/ForeignTable.rst
Documentation/Ctrl/Properties/Title.rst

[BUGFIX] Resolve rendering warnings

---

Documentation/Types/Examples.rst
Documentation/Types/Index.rst
Documentation/Types/Introduction.rst
Documentation/Types/Properties/ColumnsOverrides.rst
Documentation/Types/Properties/Showitem.rst
Documentation/Types/Properties/SubtypeValueField.rst
Documentation/Types/Properties/SubtypesAddlist.rst
Documentation/Types/Properties/SubtypesExcludelist.rst

* transfer code-blocks to new syntax

[TASK] Overhaul types

---

Documentation/Palettes/Examples.rst
Documentation/Palettes/Index.rst
Documentation/Palettes/Properties/Description.rst
Documentation/Palettes/Properties/Index.rst
Documentation/Palettes/Properties/IsHiddenPalette.rst
Documentation/Palettes/Properties/Label.rst
Documentation/Palettes/Properties/Showitem.rst

* transfer code-blocks to new syntax

[TASK] Overhaul palettes

---

Documentation/ColumnsConfig/CommonProperties/FieldControl/AddRecord.rst
Documentation/ColumnsConfig/CommonProperties/FieldControl/EditPopup.rst
Documentation/ColumnsConfig/CommonProperties/FieldControl/Index.rst
Documentation/ColumnsConfig/CommonProperties/FieldControl/ListModule.rst
Documentation/ColumnsConfig/CommonProperties/FieldControl/ResetSelection.rst
Documentation/ColumnsConfig/CommonProperties/FieldWizard/DefaultLanguageDifferences.rst
Documentation/ColumnsConfig/CommonProperties/FieldWizard/Index.rst
Documentation/ColumnsConfig/CommonProperties/FieldWizard/LocalizationStateSelector.rst
Documentation/ColumnsConfig/CommonProperties/FieldWizard/OtherLanguageContent.rst
Documentation/ColumnsConfig/CommonProperties/FieldWizard/SelectIcons.rst

[TASK] Overhaul fieldwizard and fieldcontroll

---

Documentation/ColumnsConfig/Type/Check/Default.rst
Documentation/ColumnsConfig/Type/Check/Index.rst
Documentation/ColumnsConfig/Type/Check/LabeledToggle.rst
Documentation/ColumnsConfig/Type/Check/Properties/Cols.rst
Documentation/ColumnsConfig/Type/Check/Properties/Default.rst
Documentation/ColumnsConfig/Type/Check/Properties/Eval.rst
Documentation/ColumnsConfig/Type/Check/Properties/Index.rst
Documentation/ColumnsConfig/Type/Check/Properties/InvertStateDisplay.rst
Documentation/ColumnsConfig/Type/Check/Properties/Items.rst
Documentation/ColumnsConfig/Type/Check/Properties/RenderType.rst
Documentation/ColumnsConfig/Type/Check/Properties/Validation.rst
Documentation/ColumnsConfig/Type/Check/Toggle.rst

[TASK] Overhaul check type

---

Documentation/ColumnsConfig/Type/Category/Examples.rst
Documentation/ColumnsConfig/Type/Category/Index.rst
Documentation/ColumnsConfig/Type/Category/Properties/Default.rst
Documentation/ColumnsConfig/Type/Category/Properties/ExclusiveKeys.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTable.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableItemGroup.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTablePrefix.rst
Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableWhere.rst
Documentation/ColumnsConfig/Type/Category/Properties/ItemGroups.rst
Documentation/ColumnsConfig/Type/Category/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Category/Properties/Relationship.rst
Documentation/ColumnsConfig/Type/Category/Properties/TreeConfig.rst

[TASK] Overhaul category type

---

Documentation/ColumnsConfig/Type/Color/Index.rst
Documentation/ColumnsConfig/Type/Color/Properties/Index.rst
Documentation/ColumnsConfig/Type/Color/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Color/Properties/Size.rst
Documentation/ColumnsConfig/Type/Color/Properties/ValuePicker.rst

[TASK] Overhaul color type

---

Documentation/ColumnsConfig/Type/Flex/AboutDataStructures.rst
Documentation/ColumnsConfig/Type/Flex/Examples.rst
Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst
Documentation/ColumnsConfig/Type/Flex/Properties/Ds.rst
Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerField.rst
Documentation/ColumnsConfig/Type/Flex/Properties/Index.rst

[TASK] Overhaul flex type

---

Documentation/ColumnsConfig/Type/Group/Examples.rst
Documentation/ColumnsConfig/Type/Group/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/Allowed.rst
Documentation/ColumnsConfig/Type/Group/Properties/ElementBrowserEntryPoints.rst
Documentation/ColumnsConfig/Type/Group/Properties/FieldControl.rst
Documentation/ColumnsConfig/Type/Group/Properties/FieldWizard.rst
Documentation/ColumnsConfig/Type/Group/Properties/Filter.rst
Documentation/ColumnsConfig/Type/Group/Properties/ForeignTable.rst
Documentation/ColumnsConfig/Type/Group/Properties/HideSuggest.rst
Documentation/ColumnsConfig/Type/Group/Properties/Index.rst
Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Group/Properties/PrependTname.rst
Documentation/ColumnsConfig/Type/Group/Properties/SuggestOptions.rst
Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst

[TASK] Overhaul group type

---

Documentation/ColumnsConfig/Type/ImageManipulation/Examples.rst
Documentation/ColumnsConfig/Type/ImageManipulation/Index.rst
Documentation/ColumnsConfig/Type/ImageManipulation/Properties/AllowedExtensions.rst
Documentation/ColumnsConfig/Type/ImageManipulation/Properties/CropVariants.rst
Documentation/ColumnsConfig/Type/ImageManipulation/Properties/FileField.rst
Documentation/ColumnsConfig/Type/ImageManipulation/Properties/Index.rst

[TASK] Overhaul imagemanipulation type

---

Documentation/ColumnsConfig/Type/Inline/Examples.rst
Documentation/ColumnsConfig/Type/Inline/Index.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourDisableMovingChildrenWithParent.rst
Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourEnableCascadingDelete.rst
Documentation/ColumnsConfig/Type/Inline/Properties/CustomControls.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Filter.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignDefaultSortby.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignField.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignLabel.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignMatchFields.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSelector.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSortby.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignTableField.rst
Documentation/ColumnsConfig/Type/Inline/Properties/ForeignUnique.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Index.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
Documentation/ColumnsConfig/Type/Inline/Properties/OverrideChildTCa.rst
Documentation/ColumnsConfig/Type/Inline/Properties/Size.rst
Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricField.rst
Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricLabel.rst
Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricSortby.rst

[TASK] Overhaul inline type

---

Documentation/ColumnsConfig/Type/Json/Index.rst
Documentation/ColumnsConfig/Type/Language/Examples.rst
Documentation/ColumnsConfig/Type/Language/History.rst
Documentation/ColumnsConfig/Type/Language/Index.rst
Documentation/ColumnsConfig/Type/Language/Introduction.rst
Documentation/ColumnsConfig/Type/Language/Migration.rst
Documentation/ColumnsConfig/Type/Language/Properties/Index.rst

[TASK] Overhaul json and language type

---

Documentation/ColumnsConfig/Type/Link/Index.rst
Documentation/ColumnsConfig/Type/Link/Properties/AllowedTypes.rst
Documentation/ColumnsConfig/Type/Link/Properties/Appearance.rst
Documentation/ColumnsConfig/Type/Link/Properties/Autocomplete.rst
Documentation/ColumnsConfig/Type/Link/Properties/Index.rst
Documentation/ColumnsConfig/Type/Link/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Link/Properties/Size.rst
Documentation/ColumnsConfig/Type/Link/Properties/ValuePicker.rst

[TASK] Overhaul link type

---

Documentation/ColumnsConfig/Type/None/Examples.rst
Documentation/ColumnsConfig/Type/None/Index.rst
Documentation/ColumnsConfig/Type/None/Properties/Format.rst
Documentation/ColumnsConfig/Type/None/Properties/Index.rst
Documentation/ColumnsConfig/Type/None/Properties/PassContent.rst
Documentation/ColumnsConfig/Type/None/Properties/Size.rst

[TASK] Overhaul none type

---

Documentation/ColumnsConfig/Type/Number/Index.rst
Documentation/ColumnsConfig/Type/Number/Properties/Autocomplete.rst
Documentation/ColumnsConfig/Type/Number/Properties/Format.rst
Documentation/ColumnsConfig/Type/Number/Properties/Index.rst
Documentation/ColumnsConfig/Type/Number/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Number/Properties/Range.rst
Documentation/ColumnsConfig/Type/Number/Properties/Size.rst
Documentation/ColumnsConfig/Type/Number/Properties/Slider.rst
Documentation/ColumnsConfig/Type/Number/Properties/ValuePicker.rst

[TASK] Overhaul number type

---

Documentation/ColumnsConfig/Type/Input/Index.rst
Documentation/ColumnsConfig/Type/Input/Properties/Autocomplete.rst
Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst
Documentation/ColumnsConfig/Type/Input/Properties/Index.rst
Documentation/ColumnsConfig/Type/Input/Properties/IsIn.rst
Documentation/ColumnsConfig/Type/Input/Properties/Max.rst
Documentation/ColumnsConfig/Type/Input/Properties/Min.rst
Documentation/ColumnsConfig/Type/Input/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Input/Properties/Size.rst
Documentation/ColumnsConfig/Type/Input/Properties/ValuePicker.rst

[TASK] Overhaul input type

---

Documentation/ColumnsConfig/Type/Password/Index.rst
Documentation/ColumnsConfig/Type/Password/Properties/Autocomplete.rst
Documentation/ColumnsConfig/Type/Password/Properties/Hashed.rst
Documentation/ColumnsConfig/Type/Password/Properties/Index.rst
Documentation/ColumnsConfig/Type/Password/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Password/Properties/PasswordGenerator.rst
Documentation/ColumnsConfig/Type/Password/Properties/PasswordPolicy.rst
Documentation/ColumnsConfig/Type/Password/Properties/Size.rst

[TASK] Overhaul password type

---

Documentation/ColumnsConfig/Type/Radio/Examples.rst
Documentation/ColumnsConfig/Type/Radio/Index.rst
Documentation/ColumnsConfig/Type/Radio/Properties/Index.rst
Documentation/ColumnsConfig/Type/Radio/Properties/Items.rst

[TASK] Overhaul radio type

---

Documentation/ColumnsConfig/Type/Uuid/Index.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/EnableCopyToClipboard.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/Size.rst
Documentation/ColumnsConfig/Type/Uuid/Properties/Version.rst

[TASK] Overhaul uuid type

---

Documentation/ColumnsConfig/Type/User/Index.rst

[TASK] Overhaul user type

---

Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Examples.rst
Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Index.rst
Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Properties.rst
Documentation/ColumnsConfig/Type/Text/Default/Examples.rst
Documentation/ColumnsConfig/Type/Text/Default/Index.rst
Documentation/ColumnsConfig/Type/Text/Default/Properties.rst
Documentation/ColumnsConfig/Type/Text/Properties/Cols.rst
Documentation/ColumnsConfig/Type/Text/Properties/EnableRichtext.rst
Documentation/ColumnsConfig/Type/Text/Properties/EnableTabulator.rst
Documentation/ColumnsConfig/Type/Text/Properties/Eval.rst
Documentation/ColumnsConfig/Type/Text/Properties/FixedFont.rst
Documentation/ColumnsConfig/Type/Text/Properties/Format.rst
Documentation/ColumnsConfig/Type/Text/Properties/Index.rst
Documentation/ColumnsConfig/Type/Text/Properties/IsIn.rst
Documentation/ColumnsConfig/Type/Text/Properties/Max.rst
Documentation/ColumnsConfig/Type/Text/Properties/Min.rst
Documentation/ColumnsConfig/Type/Text/Properties/Nullable.rst
Documentation/ColumnsConfig/Type/Text/Properties/RichtextConfiguration.rst
Documentation/ColumnsConfig/Type/Text/Properties/Rows.rst
Documentation/ColumnsConfig/Type/Text/Properties/Wrap.rst
Documentation/ColumnsConfig/Type/Text/T3Editor/Properties.rst
Documentation/ColumnsConfig/Type/Text/TextTable/Examples.rst
Documentation/ColumnsConfig/Type/Text/TextTable/Index.rst
Documentation/ColumnsConfig/Type/Text/TextTable/Properties.rst

[TASK] Overhaul text type

---

Documentation/BestPractises/CommonFields.rst
Documentation/BestPractises/Index.rst
Documentation/BestPractises/LanguageFields.rst
Documentation/Index.rst
Documentation/Introduction/Index.rst
Documentation/Sitemap.rst

[TASK] Overhaul common pages indentation

---

Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst

[BUGFIX] Fix links to tsconfig

---

Documentation/ColumnsConfig/Type/Inline/Index.rst

Overhaul IRRE / inline

---

Documentation/BestPractises/LanguageFields.rst

Remove screenshot for l10n_diffsource since this screenshot was for l10n_parent.
Resolves: #885

[BUGFIX] Remove misleading screenshot

---

Documentation/ColumnsConfig/Type/None/Properties/Format.rst

Corrected the documentation for the placement of UserFunc also added example how to use it.

Example Added for the use of user (UserFunc)

---

Documentation/ColumnsConfig/Type/Select/Properties/Items.rst
Documentation/Types/Properties/CreationOptions.rst
Documentation/Types/Properties/Index.rst
Documentation/Types/Properties/_creationOptions.php

References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/801 
Releases: main

[FEATURE] Auto-registration of NewContentElementWizard via TCA

---

Documentation/ColumnsConfig/Type/Group/Properties/HideSuggest.rst

See https://forge.typo3.org/issues/89414

[TASK] Document search syntax for suggest wizard

---

Documentation/ColumnsConfig/Type/Input/Index.rst

Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/937

[FEATURE] Auto create DB fields from TCA for type "input"

---

Documentation/ColumnsConfig/Type/User/Index.rst
Documentation/ColumnsConfig/Type/User/_includes/_Label.diff
Documentation/ColumnsConfig/Type/User/_includes/_SpecialFieldElement.php

Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/582

[!!!][TASK] Connect label with element in FormEngine

---

Documentation/ColumnsConfig/CommonProperties/AutoSizeMax.rst
Documentation/ColumnsConfig/CommonProperties/BehaviourAllowLanguageSynchronization.rst
Documentation/ColumnsConfig/CommonProperties/Default.rst
Documentation/ColumnsConfig/CommonProperties/DontRemapTablesOnCopy.rst
Documentation/ColumnsConfig/CommonProperties/FieldInformation.rst
Documentation/ColumnsConfig/CommonProperties/HideMoveIcons.rst
Documentation/ColumnsConfig/CommonProperties/Index.rst
Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst
Documentation/ColumnsConfig/CommonProperties/LocalizeReferencesAtParentLocalization.rst
Documentation/ColumnsConfig/CommonProperties/Maxitems.rst
Documentation/ColumnsConfig/CommonProperties/Minitems.rst
Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/CommonProperties/Mode.rst
Documentation/ColumnsConfig/CommonProperties/Multiple.rst
Documentation/ColumnsConfig/CommonProperties/Placeholder.rst
Documentation/ColumnsConfig/CommonProperties/ReadOnly.rst
Documentation/ColumnsConfig/CommonProperties/Required.rst
Documentation/ColumnsConfig/CommonProperties/Search.rst
Documentation/ColumnsConfig/CommonProperties/Size.rst
Documentation/ColumnsConfig/CommonProperties/Softref.rst
Documentation/Interface/Examples.rst
Documentation/Interface/Properties.rst

[TASK] Correct indentations and confval params

---

Documentation/ColumnsConfig/Type/Flex/Index.rst

[TASK] Bugfixes to flex page

---

Documentation/ColumnsConfig/Type/Password/_Properties/_Autocomplete.rst.txt

Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/851 

[BUGFIX] Avoid autocompletion in TCA type password

---

Documentation/ColumnsConfig/Type/Folder/_Properties/_HideDeleteIcon.rst.txt
Documentation/ColumnsConfig/Type/Group/_Properties/_HideDeleteIcon.rst.txt

[TASK] Document `hideDeleteIcon` for TCA "Group fields"

---

Documentation/Types/Index.rst

Add versionchanged information again
Follow up for #1163
Releases: main

Follow up Merge properties back into types page

---

Documentation/Types/_CodeSnippets/_creationOptions.php
Documentation/Types/_Properties/_CreationOptions.rst.txt

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/801
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/1161
Releases: main

[FEATURE] Add types > creationOptions > defaultValues

---

Documentation/guides.xml

See also https://github.com/TYPO3-Documentation/render-guides/pull/745

[TASK] Display confvals as TCA in Search facets

---

Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst
Documentation/ColumnsConfig/CommonProperties/Mm.rst
Documentation/ColumnsConfig/Type/Category/Examples.rst
Documentation/ColumnsConfig/Type/Category/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Check/_Properties/_ItemsProcFunc.rst.txt
Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst
Documentation/ColumnsConfig/Type/Group/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Inline/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Radio/_Properties/_ItemsProcFunc.rst.txt
Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTable.rst.txt
Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ForeignTable.rst.txt
Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTable.rst.txt
Documentation/ColumnsConfig/Type/Select/Single/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTable.rst.txt
Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Mm.rst.txt
Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTable.rst.txt
Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Mm.rst.txt
Documentation/Palettes/_Properties/_Description.rst.txt

[TASK] Remove TYPO3 v11.x version hints

---

Documentation/Index.rst

[TASK] Add intermediate headers in main menu

---

Documentation/ColumnsConfig/Type/Link/_Properties/_Appearance.rst.txt

[BUGFIX] For TCA type=link the TCA option is allowedFileExtensions #1227

---

Documentation/ColumnsConfig/Type/Datetime/_Properties/_DisableAgeDisplay.rst.txt

fix: replace outdated eval with format in datetime.disableAgeDisplay

---

Documentation/ColumnsConfig/Type/Color/_Properties/_Nullable.rst.txt

Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues

[BUGFIX] Display correct code example

---

Documentation/Ctrl/_Properties/_SearchFields.rst.txt

Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/1203

[BUGFIX] Replace Hook with Event

---

Documentation/ColumnsConfig/Type/Slug/_Properties/_GeneratorOptions.rst.txt

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1229
Releases: main

[FEATURE] Introduce regex based replacements for slugs

---

Documentation/ColumnsConfig/Type/Text/Default/_Properties/_Cols.rst.txt

Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/1264 
Releases: main, 13.4

Correct title

---

Documentation/ColumnsConfig/Type/Text/Default/_Properties/_Rows.rst.txt

Fix syntax

---

Documentation/ColumnsConfig/Type/Inline/_Properties/_Appearance.rst.txt

This way they can be permalinked individually.

[TASK] Turn inline appearance settings into confvals

---

Documentation/ColumnsConfig/Type/Check/_Properties/_RenderType.rst.txt

Releases: main, 13.4, 12.4, 11.5
Note that 11.5 has a different file where the properties are listed.

[BUGFIX] Change renderType type from boolean to string

---

Documentation/ColumnsConfig/Type/Passthrough/Index.rst

Passthrough field not auto created
